// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package products

import (
	"github.com/google/wire"
	"github.com/mvcatsifma/golang-wire-modules/db"
)

// Injectors from wiring.go:

func InitializeService() *Service {
	dbClient := db.NewClient()
	service := NewService(dbClient)
	return service
}

// wiring.go:

var dbClientSet = wire.NewSet(db.NewClient, wire.Bind(new(IDbClient), new(db.DbClient)))
